# Generated by Django 4.0.1 on 2022-01-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('School_Creating_Admin', '0003_school_details_schoolcountry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_register_number', models.CharField(max_length=20)),
                ('student_class', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('student_class_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('student_address', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Creating_Admin.school_details')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_subject', models.CharField(max_length=20)),
                ('teacher_address', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=10)),
                ('teacher_taking_class1', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('teacher_taking_class1_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('teacher_taking_class2', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('teacher_taking_class2_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('teacher_taking_class3', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('teacher_taking_class3_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('teacher_taking_class4', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('teacher_taking_class4_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('teacher_taking_class5', models.CharField(choices=[('empty', 'empty'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('teacher_taking_class5_section', models.CharField(choices=[('empty', 'empty'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Subjects_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_name', models.CharField(max_length=20)),
                ('student_first_subject_marks', models.CharField(max_length=5)),
                ('student_second_subject_marks', models.CharField(max_length=5)),
                ('student_third_subject_marks', models.CharField(max_length=5)),
                ('student_fourth_subject_marks', models.CharField(max_length=5)),
                ('student_fifth_subject_marks', models.CharField(max_length=5)),
                ('student_sixth_subject_marks', models.CharField(max_length=5)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Creating_Admin.school_details')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Admin_App.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_is', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th')], max_length=10)),
                ('first_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('second_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('third_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('fourth_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('fifth_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('sixth_subject', models.CharField(choices=[('NoSubject', 'NoSubject'), ('Tamil', 'Tamil'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('SocialScience', 'SocialScience'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Zoology', 'Zoology'), ('ComputerScience', 'ComputerScience')], max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Creating_Admin.school_details')),
            ],
        ),
    ]
