# Generated by Django 4.0.1 on 2022-01-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Creating_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schooladdress', models.CharField(max_length=100)),
                ('schooldistrict', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
