# Generated by Django 4.0.1 on 2022-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Creating_Admin', '0002_school_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_details',
            name='schoolcountry',
            field=models.CharField(default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='school_details',
            name='schoolstate',
            field=models.CharField(default='Tamilnadu', max_length=20),
        ),
    ]
